server:
  port: 80
spring:
  h2:
    console:
      #H2数据库页面地址：http://localhost/h2-console
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath*:schema.sql
    data: classpath*:data.sql
  application:
    name: MybatisCache

mybatis:
  enable: true
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.zhengxl.mybatiscache.entity
  configuration:
    #自动将表字段的下划线命名映射为驼峰命名
    map-underscore-to-camel-case: true
    #二级缓存总开关，mybatis默认开启二级缓存
    cache-enabled: true
    local-cache-scope: session

logging:
  level:
    com.zhengxl.mybatiscache.mapper: debug
